"""Initial migration

Revision ID: 90df5e248de3
Revises: 
Create Date: 2025-07-23 09:26:56.088881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90df5e248de3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutritions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protein', sa.String(length=255), nullable=False),
    sa.Column('carbohydrate', sa.String(length=255), nullable=False),
    sa.Column('fat', sa.String(length=255), nullable=False),
    sa.Column('fiber', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('expiryDate', sa.String(length=255), nullable=False),
    sa.Column('nutritionId', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['nutritionId'], ['nutritions.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('productId', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('info', 'warning', 'error', name='notificationtype'), nullable=False),
    sa.Column('created_at', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanlogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=False),
    sa.Column('productId', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('scanned', 'expired', 'not_found', name='scanstatus'), nullable=False),
    sa.Column('scanned_at', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanlogs')
    op.drop_table('notifications')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('nutritions')
    # ### end Alembic commands ###
